version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: bugsugi-db
    environment:
      POSTGRES_USER: bugsugi_user
      POSTGRES_PASSWORD: bugsugi_password
      POSTGRES_DB: bugsugi_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
